FROM ruby:3.3.0
ARG USER_ID=1000

RUN mkdir /app
WORKDIR /app
COPY Gemfile ./
COPY Gemfile.lock ./
RUN bundle install

COPY . .
RUN useradd guilherme --uid ${USER_ID} --create-home --shel /bin/bash && \
     chown -R guilherme:guilherme .

USER guilherme:guilherme
EXPOSE 4000
CMD ["rails", "s", "-b", "0.0.0.0", "-p", "4000"]
