FROM ruby:3.3.0
ARG USER_ID=1000

RUN mkdir /app
WORKDIR /app
RUN useradd guilherme --uid ${USER_ID} --create-home --shel /bin/bash && \
     chown -R guilherme:guilherme .

USER guilherme:guilherme
CMD
